SELECT
	INFORMATION_SCHEMA.COLUMNS.*,
	COL_LENGTH('#TableName#', INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME) AS COLUMN_LENGTH,
	COLUMNPROPERTY(OBJECT_ID('#TableName#'), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsComputed') AS IsComputed,
	COLUMNPROPERTY(OBJECT_ID('#TableName#'), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsIdentity') AS IsIdentity,
	COLUMNPROPERTY(OBJECT_ID('#TableName#'), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsRowGuidCol') AS IsRowGuidCol,
	ExtendedProperties.Value AS ProgrammaticAlias
FROM
	INFORMATION_SCHEMA.COLUMNS
	LEFT JOIN ::fn_listextendedproperty('ProgrammaticAlias', 'user', 'dbo', 'table', '#TableName#', 'column', default) AS ExtendedProperties ON INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = ExtendedProperties.objName COLLATE Chinese_PRC_CI_AS 
WHERE
	INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = '#TableName#'
